/* 首页推荐类型常量 --------- start ----------- */

///展示类型  每个类型对应一个weight组件
const SHOWTYPE_BALL = "BALL";
const SHOWTYPE_BANNER = "BANNER";
const SHOWTYPE_HOMEPAGE_SLIDE_PLAYLIST = "HOMEPAGE_SLIDE_PLAYLIST";
const SHOWTYPE_HOMEPAGE_NEW_SONG_NEW_ALBUM = "HOMEPAGE_NEW_SONG_NEW_ALBUM";
const SHOWTYPE_SLIDE_SINGLE_SONG = "SLIDE_SINGLE_SONG";
const SHOWTYPE_SHUFFLE_MUSIC_CALENDAR = "SHUFFLE_MUSIC_CALENDAR";
const SHOWTYPE_HOMEPAGE_SLIDE_SONGLIST_ALIGN = "HOMEPAGE_SLIDE_SONGLIST_ALIGN";
const SHOWTYPE_SHUFFLE_MLOG = "SHUFFLE_MLOG";
const SHOWTYPE_SLIDE_VOICELIST = "SLIDE_VOICELIST";
const SHOWTYPE_SLIDE_PLAYABLE_DRAGON_BALL = "SLIDE_PLAYABLE_DRAGON_BALL";

/* 首页推荐类型常量 --------- end ----------- */

//app内部跳转标识
const APP_ROUTER_TAG = 'orpheus';
